MW-174/Komentarze-odpowiedzi
IO2-2023-JB/team-10-backend pull request #33
Opened 2023-04-20 22:13 UTC by zagorskim

Comment responses functionality

2023-04-22 16:48 UTC, nowakmikolaj requested changes

2023-04-22 16:48 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/CommentController.cs
> +		/// All comments of particular video retrieval
opis endpointa coś nie taki

2023-04-22 16:48 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/CommentController.cs
> +			var users = (await _repository.UsersRepository.GetUsersByIds(comments.Select(x => x.AuthorId))).ToHashSet();
sprawdzałeś czy tutaj ten `ToHashSet()` działa? wydaje mi się, że nie. Trzebaby było w klasie `User` przeciążyć dwie metody i powiedzieć wprost co to znaczy że dany user jest równy drugiemu userowi. 

https://stackoverflow.com/questions/8952003/how-does-hashset-compare-elements-for-equality
![image](https://user-images.githubusercontent.com/102852926/233796332-312c4267-ed74-468b-adcc-718edac3301b.png)

2023-04-22 16:48 UTC, nowakmikolaj commented on Repository/CommentRepository.cs
> +			return (await GetAll()).Where((x) => x.VideoId == id && x.OriginCommentId == null).ToList();
pola OriginComment używasz też na froncie? czy to jest tylko dla wygody na backendzie

2023-04-22 16:48 UTC, nowakmikolaj commented on Repository/CommentRepository.cs
> +			return (await GetAll()).Where((x) => x.OriginCommentId == id).ToList();
to samo co wyżej

2023-04-22 16:48 UTC, nowakmikolaj commented on Repository/CommentRepository.cs
> +			return (await GetAll()).Where((x) => x.VideoId == id && x.OriginCommentId == null).ToList();
tutaj pobierasz wszystkie komentarze z bazy i filtrujesz je dopiero w programie. Powinieneś używać `_collection.Find((x)=> warunek).ToListAsync()` - wtedy z bazy pobierasz tylko to co potrzebujesz

2023-04-22 16:48 UTC, nowakmikolaj commented on Repository/CommentRepository.cs
> +			(await GetAll())
to samo co wyżej, mogłem na to nie zwrócić uwagi podczas poprzedniego review dla samych komentarzy, to sprawdź czy gdzieś indziej tego samego nie zrobiłeś

2023-04-22 16:48 UTC, nowakmikolaj commented on Repository/Managers/CommentManager.cs
> +									var user = users.Where((y) => x.AuthorId == y.Id).First();
a dlaczego zmieniłeś?

2023-04-23 12:40 UTC, zagorskim commented on Repository/CommentRepository.cs
> +			return (await GetAll()).Where((x) => x.VideoId == id && x.OriginCommentId == null).ToList();
na froncie nie jest potrzebna informacja czy komentarz jest odpowiedzią, czy może zwykłym komentarzem - po prostu biję pod odpowiedni endpoint

2023-04-23 12:41 UTC, zagorskim commented on Repository/Managers/CommentManager.cs
> +									var user = users.Where((y) => x.AuthorId == y.Id).First();
jak konwersację prowadziły różne konta to się psuło i nie znajdowało

2023-04-23 12:49 UTC, zagorskim commented on Repository/CommentRepository.cs
> +			return (await GetAll()).Where((x) => x.VideoId == id && x.OriginCommentId == null).ToList();
wydaje mi się, że te metody do wyciągania z bazy realizowane są leniwie i koniec końców i tak całe te chainy są łączone w jedno zapytanie, ale fakt - lepiej z findem

2023-04-23 13:30 UTC, zagorskim commented on MojeWidelo_WebApi/Controllers/CommentController.cs
> +			var users = (await _repository.UsersRepository.GetUsersByIds(comments.Select(x => x.AuthorId))).ToHashSet();
Miałeś rację, sprawdziłem.

Przeciążyłem te metody i teraz rzeczywiście działa ten HashSet.

2023-04-23 14:03 UTC, zagorskim commented on Repository/CommentRepository.cs
> +			(await GetAll())
znalazłem jeszcze jedno wystąpienie w reakcjach

2023-04-23 17:07 UTC, nowakmikolaj approved these changes
jest pięknie

2023-04-23 17:07 UTC, nowakmikolaj commented on Entities/Models/User.cs
> +			return obj is User comment && Id == comment.Id;
dlaczego comment?

2023-04-23 17:07 UTC, nowakmikolaj commented on Repository/ReactionRepository.cs
> +		public (ReactionType reactionType, string id) GetCurrentUserReaction(string videoId, string userId)
a dlaczego tutaj jednak bez asynca, awaita i .ToListAsync()?

2023-04-23 18:34 UTC, zagorskim commented on Repository/ReactionRepository.cs
> +		public (ReactionType reactionType, string id) GetCurrentUserReaction(string videoId, string userId)
a no może być i z tym

2023-04-23 18:36 UTC, zagorskim commented on Entities/Models/User.cs
> +			return obj is User comment && Id == comment.Id;
a skopiowane, zaczynalem to robic nie tam gdzie trzeba

2023-04-23 18:51 UTC, merged