Add donating and withdrawing money (virtual)
IO2-2023-JB/team-10-backend pull request #42
Opened 2023-05-16 00:28 UTC by Sosssen

eldon,
na początku pragnę zaznaczyć, że chyba lepiej zamienić AccountBalance na decimal, a nie double, bo już zauważyłem błędy zaokrągleń
po drugie, wszystko na razie jest w user repository/controller, jeżeli będzie potrzeba zmienić to jutro pod okiem szefa backendu, mikołaja, refactor

JAK TESTOWAĆ:

POST `/api/donate/send`
w query podajemy 2 parametry:
* `id` osoby, której chcemy wpłacić bilon
* `amount` czyli hajsik do przelania

co przetestować:
- jeżeli taki user jakiego id podamy nie istnieje, to 404
- jeżeli taki user nie jest twórcą, to 400
- jeżeli wszystko git, to 200 i sprawdzamy w bazie, czy AccountBalance tego usera się zwiększył

POST `/api/donate/withdraw`
w query podajemy 1 parametr:
* `amount`, czyli tyle, ile chcemy wypłacić

co przetestować:
- jeżeli nie jesteśmy twórcą, to 403
- jeżeli mamy za mało pieniędzy (mniej niż chcieliśmy wypłacić), to 400 i nie zmienia nam środków na koncie
- jeżeli alles gut, to 200 i sprawdzamy, czy AccountBalance nasz odpowiednio zmalał

elDON, DONbranoc

2023-05-16 07:38 UTC, nowakmikolaj requested changes
małe poprawki i będzie git

2023-05-16 07:38 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
nowy kontroler do tego by było fajnie

2023-05-16 07:38 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +		[ServiceFilter(typeof(ModelValidationFilter))]
ten drugi filtr chyba miałeś na myśli, bo ten sprawdza body a nie poprawność id

2023-05-16 07:38 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +		[ServiceFilter(typeof(ModelValidationFilter))]
niepotrzebny filtr, nic tu nie robi

2023-05-16 07:38 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +			var user = await _repository.UsersRepository.GetById(id);
po prostu `GetUserFromToken()` zrobi to na raz

2023-05-16 07:38 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +					"Nie można wypłacić środków, niewystarczająca ilość środków na koncie."
żeby było spójnie to zrób albo 'nie można' albo 'nie możesz' w obu komunikatach

2023-05-16 18:07 UTC, nowakmikolaj requested changes

2023-05-16 18:07 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +			}
trzeba jeszcze dodać sprawdzenie czy ktoś sam sobie nie chce wysłać

2023-05-16 21:59 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
don

2023-05-16 22:01 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +		[ServiceFilter(typeof(ModelValidationFilter))]
hehe zasugerowałem się komentarzem w filtrze, żeby go dawać do postów i putów, ale pewnie masz rację, bo ty to kminisz, don

2023-05-16 22:01 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +		[ServiceFilter(typeof(ModelValidationFilter))]
don

2023-05-16 22:01 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +			var user = await _repository.UsersRepository.GetById(id);
tak, ale potem w UpdateAccountBalance używam tego `id`, więc imo git, nie zmieniłem, odnieś się

2023-05-16 22:02 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +					"Nie można wypłacić środków, niewystarczająca ilość środków na koncie."
don

2023-05-16 22:03 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +			}
![image](https://github.com/IO2-2023-JB/team-10-backend/assets/72930007/d23e0a23-999f-4980-a0d9-7a94b8964dd9)
nikt mi nie odpowiedział, imo wysłanie samemu sobie to wpłacenie środków na konto, zaraz podbiję pytanie

2023-05-16 22:31 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +			}
don

2023-05-17 17:35 UTC, nowakmikolaj approved these changes
pppieknie

2023-05-18 20:40 UTC, merged