[SPRINT #5] Creator has to delete all videos before being able to change to basic
IO2-2023-JB/team-10-backend pull request #53
Opened 2023-05-19 20:35 UTC by H3w9VH3F4L4Tq5MbsfRi

Jak w tytule

Endpointy do testowania są w Postman -> saj

2023-05-20 13:51 UTC, nizioleque approved these changes

2023-05-21 09:47 UTC, nowakmikolaj requested changes

2023-05-21 09:47 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +				var userVideos = _repository.VideoRepository.GetVideosByUserId(id, true).Result;
nie używaj `.Result` bo to blokuje wątek, zawsze `await`

2023-05-21 11:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +				var userVideos = _repository.VideoRepository.GetVideosByUserId(id, true).Result;
FIXED

2023-05-21 11:24 UTC, nowakmikolaj approved these changes

2023-05-21 11:27 UTC, merged