Mw 156/recommendations
IO2-2023-JB/team-10-backend pull request #60
Opened 2023-06-01 16:03 UTC by zagorskim

Endpoint pythonowego zwraca tablicę rekomendacji w postaci ID filmów posortowanych względem najlepszego dopasowania. W aktualnym rozwiązaniu rekomendowane filmy są dopasowywane jedynie na podstawie odsetka tagów wspólnych z ostatnimi 10 obejrzanymi filmami. Została zastosowana prosta heurystyka zmniejszająca istotność dopasowania dawniej oglądanych filmów. Output modelu może być pusty zależnie od istnienia jakiegokolwiek sensownego dopasowania w bazie oraz istnienia historii wyświetleń requestującego użytkownika.

2023-06-01 22:22 UTC, nizioleque requested changes

2023-06-01 22:22 UTC, nizioleque commented on recommendation_engine/.vscode/settings.json
> +
- usunąć ten plik (i dodaj sobie te ustawienia do "globalnych" opcji vs code)
- albo dodać do gitignore folder .vscode

2023-06-01 22:22 UTC, nizioleque commented on recommendation_engine/app/const.py
> +DEPTH_PENALTY = 1
ogólnie do takich rzeczy polecam biblioteczkę dotenv, chyba ci kiedys o niej mowilem, wtedy takie consty mozna latwo nadpisac zmiennymi srodowiskowymi (zeby np. na maszynie produkcyjnej byl inny url czy database_name)

2023-06-01 22:22 UTC, nizioleque commented on recommendation_engine/app/const.py
> +DEPTH_PENALTY = 1
a no wlasnie, tu jest problem - na produkcji uzywamy tabeli `mojeWideloDb_Production` czy jakos tak

moja propozycja jak rozwiązać problem:
- w pliku service na VMce (`/etc/systemd/system/io2_api_search.service` chyba) dodaj linijke np. `Environment=IO2_ENVIRONMENT=Production` (zobacz readme odnośnie service'ów i jak zmienisz na maszynie to popraw readme żeby odpowiadało temu co jest na maszynie)
- wtedy tutaj w tym pliku na podstawie zmiennej srodowiskowej mozesz wybrac miedzy `mojeWideloDb` a `mojeWideloDb_Production`

2023-06-01 22:22 UTC, nizioleque commented on recommendation_engine/app/main.py
> +    recommendations = Recommendations()
czy trzeba przy każdym requeście tworzyć nową instancję tej klasy? nie mozna zrobic zmiennej "globalnej" wyzej? (taki Singleton)

2023-06-01 22:22 UTC, nizioleque commented on recommendation_engine/app/recommendations.py
> +        # todo: handle empty collections
co z tymi TODO?

2023-06-02 02:22 UTC, zagorskim commented on recommendation_engine/app/const.py
> +DEPTH_PENALTY = 1
Trochę tej linijki nie rozumiem, ale obstawiam, że tworzy zmienną środowiskową o nazwie `IO2_ENVIRONMENT` i wartości `Production`. Zerknij, czy to co stworzyłem zadziała. Muszę zrobić rebase zanim uzupełnię README, bo jeszcze nie mam na tym branchu wpisu o serwisie silnika rekomendacji. Wykorzystałem paczkę `python-dotenv` jak coś, 2 pliki ze zmiennymi dla produkcji i deva - fajna opcja rzeczywiście.

2023-06-02 09:02 UTC, nizioleque approved these changes

2023-06-02 09:24 UTC, merged