[MW-234] Recommendation endpoint actual logic
IO2-2023-JB/team-10-backend pull request #67
Opened 2023-06-02 06:53 UTC by H3w9VH3F4L4Tq5MbsfRi

!!!! WPIERW ZMERGOWAĆ https://github.com/IO2-2023-JB/team-10-backend/pull/60 !!!!

Endpoint bierze rekomendacje dla danego użytkownika i dopełnia je do minimum 10ciu filmów (jeżeli tyle jest w bazie)

Testowanie: XD

2023-06-02 09:19 UTC, nizioleque requested changes

2023-06-02 09:19 UTC, nizioleque commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			using HttpClient client = new();
ten using w ogóle coś robi? nie powinno być klamerek? jak to działa

2023-06-02 09:19 UTC, nizioleque commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var vIDs = JsonSerializer.Deserialize<IEnumerable<RecommendationDto>>(json);
co to za dziwna nazwa? nikt poza tobą nie wie co to jest po przeczytaniu nazwy zmiennej

2023-06-02 09:19 UTC, nizioleque commented on Repository/VideoRepository.cs
> +			IEnumerable<RecommendationDto> vIDs,
też nazwa

2023-06-02 09:19 UTC, nizioleque commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var vIDs = JsonSerializer.Deserialize<IEnumerable<RecommendationDto>>(json);
poza tym to nie jest poprawny camelCase - po przetlumaczeniu na snake_case wyszloby `v_i_ds` a nie `v_ids`

2023-06-02 09:19 UTC, nizioleque commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			using HttpClient client = new();
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/using - tu wszędzie po using są klamerki i ta tworzona zmienna wtedy jest dostępna wewnątrz tych klamerek, po to jest using

2023-06-02 09:19 UTC, nizioleque commented on Repository/VideoRepository.cs
> +		public async Task<IEnumerable<VideoMetadata>> GetMoreVideosToRecommend(
coś ci tu nie działa kolego

zrobiłem następujący test:

python zwraca 6 filmów

wtedy c# dodaje tylko 1 - w sumie 7. Miało być 10, nie?

2023-06-02 09:41 UTC, H3w9VH3F4L4Tq5MbsfRi commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			using HttpClient client = new();
https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient#make-http-requests

MS poleca robić tak jak ja zrobiłem, więc zostawiam

2023-06-02 09:41 UTC, H3w9VH3F4L4Tq5MbsfRi commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var vIDs = JsonSerializer.Deserialize<IEnumerable<RecommendationDto>>(json);
zmieniłem na videoIDs

2023-06-02 09:42 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Repository/VideoRepository.cs
> +			IEnumerable<RecommendationDto> vIDs,
done

2023-06-02 10:03 UTC, nowakmikolaj requested changes

2023-06-02 10:03 UTC, nowakmikolaj commented on Repository/VideoRepository.cs
> +				}
zrobić z tego `HashSet` i przeciążyć odpowiednie metody w klasie `VideoMetadata` żeby hashset wiedział co to znaczy że dwa video są sobie równe

2023-06-02 10:03 UTC, zagorskim approved these changes

2023-06-02 10:03 UTC, zagorskim commented on Repository/VideoRepository.cs
> +				toReturn.Add(await GetById(v.video_id));
Nie masz tam metody `videoIDs.toList()` przypadkiem?

2023-06-02 10:03 UTC, zagorskim commented on Repository/VideoRepository.cs
> +						&& video.ProcessingProgress == ProcessingProgress.Ready
Tutaj przyszłościowo możesz dodać warunek, żeby nie wrzuciło filmu subskrybowanego twórcy - po to jest zakładka subscriptions i rekomendacje mają w przyszłości unikać tego typu filmów rónież w silniku.

2023-06-02 10:03 UTC, zagorskim commented on Repository/VideoRepository.cs
Idzie tą metodę rzeczywiście przebudować ładniej, Mikołaj wspomniał na grupie, ale no mało czasu.

2023-06-02 10:04 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Entities/Data/Playlist/RecommendationDto.cs
> +		public string video_id { get; set; }
to uwaga do Zagora, on mi takiego JSONa dał

2023-06-02 10:06 UTC, H3w9VH3F4L4Tq5MbsfRi commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var videoIDs = JsonSerializer.Deserialize<IEnumerable<RecommendationDto>>(json);
dobre

2023-06-02 10:10 UTC, nizioleque approved these changes

2023-06-02 10:15 UTC, nowakmikolaj commented on Entities/Data/Playlist/RecommendationDto.cs
> +		public string video_id { get; set; }
to się robi jakimś [JsonProperty()] przed polem czy coś takiego i dajesz tam nazwe jaka jest w jsonie i on to mapuje, na s6

2023-06-02 10:16 UTC, nowakmikolaj approved these changes

2023-06-02 10:22 UTC, merged

2023-06-14 23:24 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			using HttpClient client = new();
DONE

2023-06-14 23:40 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var json = await client.GetStringAsync("http://localhost:8000/recommendations/" + user.Id);
DONE

2023-06-14 23:54 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var videoIDs = JsonSerializer.Deserialize<IEnumerable<RecommendationDto>>(json);
DONE

2023-06-15 21:03 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Entities/Data/Playlist/RecommendationDto.cs
> +		public string video_id { get; set; }
DONE

2023-06-15 22:03 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Repository/VideoRepository.cs
> +				}
JEDNAK CHUJ

2023-06-15 22:17 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Repository/VideoRepository.cs
> +				}
HASHSET PSUJE GITHUB ACTION
ZOSTAJE

2023-06-15 22:42 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Repository/VideoRepository.cs
> +				toReturn.Add(await GetById(v.video_id));
Czytaj uważnie
Ja tutaj konkretnego po konkretnym polu szukam.

2023-06-16 08:06 UTC, H3w9VH3F4L4Tq5MbsfRi commented on Repository/VideoRepository.cs
> +						&& video.ProcessingProgress == ProcessingProgress.Ready
DONE