Add filtering videos by processing progress
IO2-2023-JB/team-10-backend pull request #72
Opened 2023-06-11 01:22 UTC by Sosssen

MW-248

już nigdzie nie powinny się wyświetlać video z processing progressem innym niż ready
jak coś przegapiłem to SORY

eldon.

2023-06-12 20:39 UTC, nowakmikolaj requested changes
drobiazg

2023-06-12 20:39 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			videos = videos.Where(x => x.ProcessingProgress == ProcessingProgress.Ready);
to samo można zrobić w PUT playlist/details dla spójności

2023-06-12 20:39 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/SearchController.cs
> +			videos = videos.Where(x => x.ProcessingProgress == ProcessingProgress.Ready);
to filtrowanie możesz wrzucić do `GetAllVisibleVideos`, my bad, tam powinienem to dać od początku

2023-06-15 01:19 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			videos = videos.Where(x => x.ProcessingProgress == ProcessingProgress.Ready);
done

2023-06-15 16:41 UTC, nowakmikolaj approved these changes

2023-06-15 21:14 UTC, nowakmikolaj approved these changes

2023-06-15 21:16 UTC, merged