Add logic for administrator
IO2-2023-JB/team-10-backend pull request #73
Opened 2023-06-11 02:02 UTC by Sosssen

Dodanie logiki do admina

pytania które zadałem na pv Mikołajowi i mamy się nad nimi zastanowić (wrzucam tu, jak ktoś chce się włączyć do dyskusji, to pv):
1. czy admin może edytować playlistę (imo nie, po co)
2. czy admin może usunąć film z playlisty (imo nie, może usunąć playkę, ale po co usuwać film z playki? to wsm to samo co w 1.)
3. czy w wyszukiwaniu adminowi powinny pokazywać się prywatne filmy, prywatne playki, czy tylko jak wejdzie się na profil użytkownika? (tutaj nwm co myśleć, więc na razie nie zaimplementowałem, wymagałoby przerobienia twoich funkcji w Search)
4. czy w registerUser nie powinienem sprawdzać czy ktoś nie próbuje zostać adminem? XD przecież można by wtedy z postmana się adminem kurwa stawać, to jest błąd security taki, że głowa mała (na razie to dodałem, odnieś się pls)
5. czy jest gdzieś opcja żeby usunąć własne konto? bo na razie endpoint deleteUser wygląda tak, że tylko id podajemy, więc znowu w postmanie może se ktokolwiek usunąć kogokolwiek xdd (na razie dodaję, że tylko admin może to użyć, nie będzie można usunąć nawet własnego konta)
6. w GetAllVideos to samo co w 3.
7. w GetVideosSubscribed to samo co w 3.

eldon.

2023-06-12 20:59 UTC, nowakmikolaj approved these changes
g

2023-06-12 20:59 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var user = await _repository.UsersRepository.GetById(userId);
za jednym razem - `var user = await GetUserFromToken()`

2023-06-12 20:59 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/VideoController.cs
> +			var user = await _repository.UsersRepository.GetById(userId);
to samo co wyżej

2023-06-14 19:45 UTC, nowakmikolaj requested changes
tak mi jeszcze się przypomniało, przy wyszukiwaniu przefiltruj userów tak żeby adminy się nie wyświetlały

2023-06-15 01:30 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/PlaylistController.cs
> +			var user = await _repository.UsersRepository.GetById(userId);
tutaj akurat potrzebuję userId i tak w L178:
```
&& userId != playlist.AuthorId
```

2023-06-15 01:31 UTC, Sosssen commented on MojeWidelo_WebApi/Controllers/VideoController.cs
> +			var user = await _repository.UsersRepository.GetById(userId);
w sumie to samo co wyżej xd L124:
```
				&& userId != video.AuthorId
```

2023-06-15 01:36 UTC, Sosssen commented
> podczas robienia admina na froncie zauważyłem że potrzeba:
> 
> * przy wyszukiwaniu przefiltrować userów tak żeby adminy się nie wyświetlały
> * w UserProfile przy mapowaniu z `User` na `UserDto` pole `AccountBalance` ma się zachowywać identycznie jak `SubscriptionsCount`, czyli być nullem dla zwykłego usera i admina
> 
> na razie tyle

done

2023-06-15 16:44 UTC, nowakmikolaj approved these changes

2023-06-15 20:37 UTC, merged