[MW-263] User removal also removes all his subscripions
IO2-2023-JB/team-10-backend pull request #81
Opened 2023-06-15 22:58 UTC by H3w9VH3F4L4Tq5MbsfRi

2023-06-15 23:02 UTC, Sosssen approved these changes
GRUN

2023-06-15 23:06 UTC, nowakmikolaj requested changes

2023-06-15 23:06 UTC, nowakmikolaj commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +
1. nie senderId, bo jak admin usuwa konto to mu wywalasz suby
2. usuwasz tylko to, co user subuje, a nie to kto go subuje, tu trzeba też wywalić te suby które zwróci `GetCreatorSubscriptions` (jeśli usuwany user jest creatorem). Więc zrób listę do której wrzucisz wszystkie suby i wtedy pętla zostaje tak jak jest

2023-06-16 05:34 UTC, H3w9VH3F4L4Tq5MbsfRi commented on MojeWidelo_WebApi/Controllers/UsersController.cs
> +
![image](https://github.com/IO2-2023-JB/team-10-backend/assets/116811873/0145fa32-593a-44a0-8e3f-9e3fd30ef2eb)

2023-06-16 08:13 UTC, merged